### ISSUE TITLE
Add link to issues

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry-console#204] opened 2019-01-22 10:50 UTC
Now that [this is live](https://registry.gbif.org) and the GBIF data administrators are using it daily, can you please add a link in the footer called "Report issue" that brings users to the github issues page?

**Comment by MortenHofft** [comment] 2019-01-22 11:16
closed as duplicate of https://github.com/gbif/registry-console/issues/193

**Closed by MortenHofft** 2019-01-22 11:16 UTC
